readme and installation updates
insightsengineering/teal.transform pull request #155
Opened 2023-09-11 13:25 UTC by m7pr

Related to https://github.com/insightsengineering/coredev-tasks/issues/462

TODO: add usage code or fi

2023-09-12 11:12 UTC, averissimo commented on README.md
>  install.packages('teal.transform', repos = c('https://insightsengineering.r-universe.dev', 'https://cloud.r-project.org'))
Something that I've been wondering on other READMEs, is there a reason not to use `getOption("repos")` instead of hardcoding the mirror?

```suggestion
install.packages('teal.transform', repos = c('https://insightsengineering.r-universe.dev', getOption('repos')))
```

2023-09-18 13:30 UTC, averissimo commented
3 of the vignettes still have dates

The patch below should do take care of it :-)

```diff
diff --git a/vignettes/data-extract-merge.Rmd b/vignettes/data-extract-merge.Rmd
index 27e07d5..ab7edfa 100644
--- a/vignettes/data-extract-merge.Rmd
+++ b/vignettes/data-extract-merge.Rmd
@@ -1,7 +1,6 @@
 ---
 title: "Combining data-extract with data-merge"
 author: "NEST coreDev"
-date: "2022-05-03"
 output: rmarkdown::html_vignette
 vignette: >
   %\VignetteIndexEntry{Combining data-extract with data-merge}
diff --git a/vignettes/data-extract.Rmd b/vignettes/data-extract.Rmd
index d0be24f..f46ab69 100644
--- a/vignettes/data-extract.Rmd
+++ b/vignettes/data-extract.Rmd
@@ -1,7 +1,6 @@
 ---
 title: "Data extract"
 author: "NEST coreDev"
-date: "2022-05-03"
 output: rmarkdown::html_vignette
 vignette: >
   %\VignetteIndexEntry{Data extract}
diff --git a/vignettes/data-merge.Rmd b/vignettes/data-merge.Rmd
index f4d0f5e..f6f0423 100644
--- a/vignettes/data-merge.Rmd
+++ b/vignettes/data-merge.Rmd
@@ -1,7 +1,6 @@
 ---
 title: "Data merge"
 author: "NEST coreDev"
-date: "2022-05-11"
 output: rmarkdown::html_vignette
 vignette: >
   %\VignetteIndexEntry{Data merge}
```

2023-09-18 18:13 UTC, donyunardi requested changes
Thanks @m7pr for looking into this!

Here are additional comments that I noticed:
* Can we remove the date on all vignettes? Other than `teal-transform.Rmd`, we still have the date.
* Should we capitalize vignette's title? For example, in `data-merge.Rmd` title, update "Data merge" to "Data Merge" (capital M)?

2023-09-18 18:13 UTC, donyunardi commented on vignettes/data-merge.Rmd
> +General datasets do not share the same relationships as `CDISC` datasets thus these relationships must be specified by the `join_keys` functions. For more information, please refer to the `Join Keys`
```suggestion
General datasets do not share the same relationships as `CDISC` datasets thus these relationships must be specified by the `join_keys` functions. For more information, please refer to the `Join Keys` [vignette](https://insightsengineering.github.io/teal.data/latest-tag/articles/join-keys).
```

JoinKeys is in teal.data

2023-09-18 19:49 UTC, donyunardi requested changes

2023-09-18 19:49 UTC, donyunardi commented on vignettes/teal-transform.Rmd
>  author: "NEST coreDev"
```suggestion
author: "NEST CoreDev"
```

To be consistent with the rest of teal's vignettes.
Can we also make the same update with `data-merge.Rmd`?

2023-09-19 08:32 UTC, chlebowa commented on README.md
> +ADSL <- teal.transform::rADSL
If we run `library`, why prefix `rADSL`?

2023-09-19 13:08 UTC, m7pr commented on vignettes/teal-transform.Rmd
>  author: "NEST coreDev"
Hey, I just changed coreDev to CoreDev + removed dates

2023-09-19 18:34 UTC, donyunardi commented
This line is repeated twice:
https://github.com/insightsengineering/teal.transform/blob/16c428000cce9f8f1cc206c54ed7753ceb2f9935/vignettes/data-merge.Rmd#L189-L190

I'll remove 189 and approve this PR.

2023-09-19 18:38 UTC, donyunardi commented
`%\VignetteIndexEntry` also need to be updated to match the new title. I'll update this as well.

2023-09-19 18:47 UTC, donyunardi approved these changes
LGTM!

2023-09-19 18:52 UTC, merged

2023-09-20 08:28 UTC, m7pr commented
Agh, thanks @donyunardi for catching that!