`tdata` to `teal_data`
insightsengineering/teal.transform pull request #163
Opened 2023-11-23 08:48 UTC by gogonzo

This is a feature branch, **DON'T MERGE and DON'T COMMENT**. PR open to have a constant checks. We will start review this PR as a whole in the sprint 4.

2023-11-23 08:52 UTC, chlebowa requested changes
blocked

2023-12-07 11:08 UTC, chlebowa commented on R/data_extract_module.R
> +  # convert teal_data to list of reactives
```suggestion
  # convert reactive containing teal_data to list of reactives with one dataset each
```

2023-12-07 11:15 UTC, chlebowa commented on R/resolve.R
> +#' @param ds (`data.frame`) dataset on which the function is applied to.
```suggestion
#' @param ds (`data.frame`)
```

2023-12-07 11:20 UTC, chlebowa commented on tests/testthat/test-data_extract_multiple_srv.R
>      )
```suggestion
    expr = testthat::expect_no_error(
      data_extract_multiple_srv(data_extract = list(test = NULL), datasets = mock_datasets)
    )
```

2023-12-07 11:22 UTC, chlebowa commented on tests/testthat/test-data_extract_srv.R
>      )
```suggestion
    expr = testthat::expect_no_error(
      data_extract_srv(
        id = "x",
        data_extract_spec = adsl_extract,
        datasets = data_list,
        join_keys = join_keys
      )
   )
```

2023-12-07 15:08 UTC, averissimo commented on R/resolve.R
> +#' @param ds (`data.frame`)
hahahaha true, but it should say something, having just the datatype seems odd.

Even if it just unpacks the abbreviation :shrug: 

```suggestion
#' @param ds (`data.frame`) Dataset.
```

2023-12-08 11:13 UTC, chlebowa approved these changes

2023-12-08 12:35 UTC, merged