[Docs] Refine the vignettes
insightsengineering/teal.transform pull request #199
Opened 2024-02-15 06:36 UTC by vedhav

Closes #185 

Changes:
1. Updated the diagram so it's more clear on what teal.transform does.
2. Added a small vignette explaining how to create `data_extract_spec`
3. Update the existing vignette's example code without `teal.widgets` dependency as it's not needed.
4. Added a small note at the top of every vignette warning that the functions might change.
5. Refined the vignettes 

TODO:
1. Update the getting started vignette to include a high-level update and link the new vignette.
2. Check the vignettes for any grammar errors and things like that.
3. Add the screenshot of the app outputs in the examples.

2024-02-15 13:40 UTC, chlebowa requested changes

2024-02-15 13:40 UTC, chlebowa commented on vignettes/app-developer.Rmd
> +This object is used by the module to create the UI which the app user can control and server logic that helps in translating the UI into `R` expressions to get the data requested by the app user.
Are we sure we "R" should be backticked? I don't believe it is common to do to names of languages.

2024-02-15 13:40 UTC, chlebowa commented on vignettes/app-developer.Rmd
The article needs a proper preface, it jumps into the deep end immediately.

The graph is marginally helpful but I don't quite like its irregular appearance. Can it be shaped so that arguments unfold vertically rather than burst outwards in all directions?

2024-02-15 13:40 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
It seems to me the user has no influence on merging and transforming data whatsoever. The app developer specifies all operations, the can merely subset data that undergoes the transformations.

2024-02-15 13:40 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
> +We render this expression and evaluate it to get the final `ANL` dataset which is also rendered as a table in our UI.
What do you mean by rendering an expression?

2024-02-15 13:40 UTC, chlebowa commented on vignettes/data-extract.Rmd
> +In these situations, the developers need to let the users control the application by giving the users some degree of freedom.
These two sentences are essentially duplicates.

2024-02-15 13:40 UTC, chlebowa commented on vignettes/data-extract.Rmd
> +Examples can be found in the `teal.modules.clinical`.
```suggestion
Examples can be found in the `teal.modules.clinical` package.
```

2024-02-15 13:40 UTC, chlebowa commented on vignettes/data-extract.Rmd
> +A `teal` module can leverage by using the `data_extract_spec` objects and to handle and process the user input.
leverage what?

2024-02-15 13:43 UTC, vedhav commented on vignettes/app-developer.Rmd
> +This object is used by the module to create the UI which the app user can control and server logic that helps in translating the UI into `R` expressions to get the data requested by the app user.
We used it in [some places](https://insightsengineering.github.io/teal/latest-tag/articles/teal-options.html) earlier. I could go either way. Slightly leaning towards having backtick because it becomes easier to see it.

2024-02-15 13:47 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
> +We render this expression and evaluate it to get the final `ANL` dataset which is also rendered as a table in our UI.
```suggestion
We evaluate this expression to get the final `ANL` dataset which is also rendered as a table in our UI.
```

How about now?

2024-02-15 13:47 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
> +We render this expression and evaluate it to get the final `ANL` dataset which is also rendered as a table in our UI.
No wait. I remember what I meant. Let me rephrase it.

2024-02-15 13:49 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
> +We render this expression and evaluate it to get the final `ANL` dataset which is also rendered as a table in our UI.
```suggestion
We print this expression in the UI  and also evaluate it to get the final `ANL` dataset which is also displayed as a table in the UI.
```

Is this clear now? I wanted to convey that this object is now used to create two outputs in the UI, one is the print output of the expression and the other is the table. It would be easier to see this once we add a screenshot.

2024-02-15 13:53 UTC, vedhav commented on vignettes/data-extract.Rmd
> +In these situations, the developers need to let the users control the application by giving the users some degree of freedom.
Agreed, I'll remove this line completely.

2024-02-15 14:02 UTC, vedhav commented on vignettes/data-extract.Rmd
> +A `teal` module can leverage by using the `data_extract_spec` objects and to handle and process the user input.
```suggestion
A `teal` module can leverage using the `data_extract_spec` objects to handle and process the user input.
```

2024-02-15 14:06 UTC, vedhav commented on vignettes/app-developer.Rmd
On second thoughts I'm rethinking the diagram now. It would be better to give code snippets of different combinations of valid `des` creations.

2024-02-15 14:08 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
Yeah, this is true. From what I see, the merge operations are just a function of using the `join_keys` to perform the joins and the app user has nothing to do with this.

2024-02-15 14:36 UTC, averissimo reviewed
I like the changes, but after seeing the PR I get the feeling the window to get this reviewed and merged is too narrow.

As the vignettes would benefit from more details that would delay the release to CRAN.

On the other hand, adding that detail to deprecated it soon™ may not warrant doing it.

2024-02-15 14:36 UTC, averissimo commented on vignettes/app-developer.Rmd
> +---
Consider just merging the information on this vignette with the existing section on `data_extract_spec` in the "data-extract.Rmd"

It seems like this should be extended somewhat more to be a standalone vignette

Maybe place a section on the other that focus towards app developers.

2024-02-15 14:36 UTC, averissimo commented on vignettes/app-developer.Rmd
> +_Note that `teal.transform` is about to undergo a refactor so the functions in this vignette are subject to change._
Agree, this might discourage adoption and we're not 100% sure about when the refactor is going to happen.. next month, next semester, next year?

2024-02-15 14:36 UTC, averissimo commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
I like the flow of this document :+1:

2024-02-15 14:36 UTC, averissimo commented on vignettes/data-extract.Rmd
> +Examples can be found in the `teal.modules.clinical` package.
Add links to tmc documentation page?

2024-02-15 14:36 UTC, averissimo commented on vignettes/app-developer.Rmd
> +<img src="images/data_extract_spec.svg" alt="How to use data_extract_spec()" style="width: 100%;" />
This is a very complicated diagram, I'm not sure we can get a quick view of how we use these functions :face_with_spiral_eyes: 

Maybe add a bullet point description of the helper functions to reference them

2024-02-15 14:40 UTC, vedhav commented on vignettes/app-developer.Rmd
> +<img src="images/data_extract_spec.svg" alt="How to use data_extract_spec()" style="width: 100%;" />
> On second thoughts I'm rethinking the diagram now. It would be better to give code snippets of different combinations of valid des creations.

2024-02-15 14:46 UTC, vedhav commented on vignettes/app-developer.Rmd
> +_Note that `teal.transform` is about to undergo a refactor so the functions in this vignette are subject to change._
Removed them.

2024-02-15 14:46 UTC, vedhav commented on vignettes/data-extract.Rmd
> +Examples can be found in the `teal.modules.clinical` package.
Sure thing!

2024-02-15 17:12 UTC, vedhav commented on vignettes/app-developer.Rmd
> +This object is used by the module to create the UI which the app user can control and server logic that helps in translating the UI into `R` expressions to get the data requested by the app user.
Feel free to reopen if you feel strongly about this.

2024-02-15 17:14 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
> +We render this expression and evaluate it to get the final `ANL` dataset which is also rendered as a table in our UI.
This is just explaining what we're doing in the example app created in the vignette. Not the logic behind what is going on. I've added the screenshot of the app now. Does it make things clear now?

2024-02-15 17:16 UTC, vedhav commented on vignettes/data-extract.Rmd
> +A `teal` module can leverage by using the `data_extract_spec` objects and to handle and process the user input.
does this make sense?

2024-02-15 17:18 UTC, vedhav commented on vignettes/app-developer.Rmd
> +---
I think we can completely remove this. I added a vignette to talk about `data_extract_spec` thinking that this is the only app developer-facing function. But I feel that this is not the case as tmc does not seem to work with this. So, talking about this seems useless.

2024-02-16 09:14 UTC, averissimo commented
> What do you both think about removing the app-developer completely?

Agree! :+1:

2024-02-16 10:51 UTC, chlebowa commented
> What do you both think about removing the `app-developer` completely?

Agreed :+1:

2024-02-16 11:59 UTC, chlebowa requested changes

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
> +This gives the app user flexibility to transform the data as per their requirements.
```suggestion
`teal.transform` allows the app user to oversee transforming a relational set of data objects into the final dataset for analysis.
User actions create a R expression that subsets and merges the input data.
```

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
Please don't use contractions (like "don't").
Remember to always backtick package names (here: `shiny`).
Maintain the same case across all section titles.

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
> +For example, let's try to create an analysis dataset `ANL` by:
`In the following example we will[...]`

Add somewhere: "Note that primary key columns are maintained when selecting columns from datasets."

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
`choices = c("AGE", "BMRKR1"),` limiting choices is not connected to the essence of the example (user selecting a column). Can this be set to all columns? As a non-user: is there an easy way to say "all columns allowed"?

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
```suggestion
#### Step 1/5 - Creating data extract specifications
```

What is created is extract _specs_, not data extracts (those will be created in the srv functions and merged). Consider changing variable names accordingly.

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
> +We render this expression and evaluate it to get the final `ANL` dataset which is also rendered as a table in our UI.
Oooh, I see. That's better.

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
> +This function gets the `datasets` as a list of reactive `data.frame`, the list of `data_extract` objects, and the `join_keys` object as input.
```suggestion
This function takes as arguments the datasets (as a list of reactive `data.frame`), the data extract specifications created above (the `data_extract` list), and the `join_keys` object.
```

`join_keys` has not been mentioned before. Add some explanation somewhere or at least change `the` to `a` and add a link to `teal.data` here.

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
>  The `data_extract_srv` module depends on a list of reactive or non-reactive `data.frame` objects.
```suggestion
The `data_extract_srv` module takes as argument a list of reactive or non-reactive `data.frame`s. 
```

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
>  The `data_extract_srv` module depends on a list of reactive or non-reactive `data.frame` objects.
`data_extract_srv` is not called in this section so I'm not sure the flow is correct.

Maybe preparing data and joining keys should be step 1? It would be a good place to mention `join_keys`.

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
>  using the `data_extract`s defined in the first code block and the `datasets` object:
```suggestion
Finally, we include appropriate `merge_ui` and `merge_srv` calls in the UI and server of our `shiny` app, respectively.
```

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-extract.Rmd
>  analyze within the module.
Still some redundancy here.

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-merge.Rmd
> +Combining datasets is an essential step when working with multiple datasets.
```suggestion
Combining datasets is an essential step when working with relational datasets.
```
datasets -> data models?

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-merge.Rmd
> +Combining datasets is an essential step when working with multiple datasets.
There is a `merge` function in `base`, I don't think we have to explain what we mean by merging. The next sentence could be skipped.

Alternatively, start with "joining" instead of "combining" as that is the standard SQL term.

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-merge.Rmd
> +1. `merge_expression_module` can be used when there is no need to process the `data_extract` list.
`data_extract` is an arbitrary variable name, explain that it refers to a list of `des` objects.

2024-02-16 11:59 UTC, chlebowa commented on vignettes/data-merge.Rmd
> +#### Step 4/5 - Preparing the Data
As in the other vignette, creating the data may be a better place to start.

2024-02-16 12:27 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
>  The `data_extract_srv` module depends on a list of reactive or non-reactive `data.frame` objects.
It should be `merge_expression_srv`.
The `data_extract_srv`, `merge_expression_srv`, and `merge_expression_module` can be used in the module server along with `data_extract_ui` in the module UI.

2024-02-16 12:28 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
>  The `data_extract_srv` module depends on a list of reactive or non-reactive `data.frame` objects.
I'll remove it here. Looks like it was a copy paste from the other vignette. We already explained about `merge_expression_srv` above.

2024-02-16 12:30 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
>  The `data_extract_srv` module depends on a list of reactive or non-reactive `data.frame` objects.
Removed in both the places. They are completely redundant.

2024-02-16 12:36 UTC, vedhav commented on vignettes/data-merge.Rmd
> +#### Step 4/5 - Preparing the Data
I'll follow this order.
Data -> DES creation -> Module UI + Server -> Shiny app

2024-02-16 12:46 UTC, vedhav commented on vignettes/data-merge.Rmd
> +1. `merge_expression_module` can be used when there is no need to process the `data_extract` list.
It should have been a list of `data_extract_spec`. I have changed it.

2024-02-16 12:56 UTC, vedhav commented on vignettes/data-extract.Rmd
>  analyze within the module.
I think the first line can go.

2024-02-16 12:57 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
I don't quite understand what you mean. Could you elaborate?

2024-02-16 13:29 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
First you say 
```
1. Selecting the column `AGE` from `ADSL`
```
and then you show
```
adsl_extract <- data_extract_spec(
  dataname = "ADSL",
  select = select_spec(
    label = "Select variable:",
    choices = c("AGE", "BMRKR1"),
    selected = "AGE",
    multiple = TRUE,
    fixed = FALSE
  )
)
```

It is not obvious why I am only allowed to choose from `AGE` and `BMRKR1`.

2024-02-16 14:00 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
Okay, I see your point. I'll change it to `names(ADSL)` in all the places.

2024-02-16 14:02 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
Not in the extract vignette because we mention `select a variable from c("BMRKR1", "AGE")`

2024-02-16 14:06 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
But wait a minute if we do this, The UI will also have the primary keys, which will not be removed even if they stay unselected. Which might be odd. Perhaps the best thing to do is to just mention that we also limit the choices to select from. But I think it's self-explanatory. What do you think?

2024-02-16 14:08 UTC, chlebowa commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
We can mention that the app dev can limit the user's choice, yes. But take care that it does not distract from the core idea of the user selecting columns to keep.

As for keys, is it possible to not select them? They are automatically included when only `AGE` is selected, aren't they?

2024-02-16 14:12 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
Made the `choices = c("AGE", "SEX", "BMRKR1")` for `ADSL` and `choices = c("AVAL", "AVALC", "ASEQ")` for `ADTTE` as the diagram simulates those are the available columns before the selection.

2024-02-16 14:16 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
Irrespective of the user selecting the key columns they will be selected by `teal.transform` so this feels like a bug for the app user.
I will add a comment about the ability to restrict the option choices, as it's an important feature to showcase.

2024-02-16 14:30 UTC, vedhav commented on vignettes/data-extract-merge.Rmd
> +#### Step 1/5 - Creating the data extract
How does it look now?
 
<img width="757" alt="Screenshot 2024-02-16 at 8 00 38 PM" src="https://github.com/insightsengineering/teal.transform/assets/49812166/a0b745ea-9e95-4094-900e-a01101d58d4f">

2024-02-16 16:04 UTC, chlebowa approved these changes
Well done @vedhav :+1:

2024-02-16 16:13 UTC, vedhav commented on vignettes/data-extract.Rmd
>  from the UI to the module itself.
I agree that it was not clear here but after reading the whole vignette it becomes clear what this `module` means.
To keep it accurate and easier I'll rephrase it like this:
```
The role of `data_extract_spec` is twofold: to create a UI component in a `shiny` application and to pass user input 
from the UI to a custom server logic that can use this input to transform the data.
```

2024-02-16 16:14 UTC, vedhav commented on vignettes/data-extract.Rmd
>  from the UI to the module itself.
Thanks for the review @chlebowa that was a nice improvement suggestions along the way.

2024-02-16 16:14 UTC, merged